### ISSUE TITLE
修正 TU 指出的錯誤

### ISSUE THREAD

**Issue by rileychh** [NTUT-NPC/AoA#2]
https://discord.com/channels/874624266660888636/1131604199885520916/1318129861826711634

修正時的 commit description 要加上 `Co-Authored-By: Tien Yu Lin <trusaidlin@gmail.com>`

**Comment by Xanonymous-GitHub** [comment]
```diff
-修正時的的
+修正時的
```

**Comment by kevinlee-06** [comment]
已開 PR https://github.com/NTUT-NPC/AoA/pull/3
